services:
  sgtm:
    image: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    container_name: sgtm
    environment:
      CONTAINER_CONFIG: ${CONTAINER_CONFIG}   # kommt aus .env
      RUN_AS_UID: 0
      RUN_AS_GID: 0
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - sgtm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro   # wichtig: Pfad ohne /caddy/
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
